# -*- coding: utf-8 -*-
"""login.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oRB7_fK3dmfZCnjAH8XnvZIZqzBYRC6D
"""

import streamlit as st
import authlib
IMAGE_ADDRESS = "concussion.jpeg"
if not st.user.is_logged_in:
  st.title("Welcome to the Concussion Detection App! ")
  st.image(IMAGE_ADDRESS)
  if st.sidebar.button("Log in with Google", type="primary", icon=":material/login:"):
        st.login()

else:
  st.subheader("Please visit the app")
  if st.sidebar.button("Log out", type="secondary", icon=":material/logout:"):
        st.logout()
