# -*- coding: utf-8 -*-
"""login.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oRB7_fK3dmfZCnjAH8XnvZIZqzBYRC6D
"""

import streamlit as st
import authlib
IMAGE_ADDRESS = "https://www.theglobeandmail.com/resizer/v2/ZEC33ARWYNF7JKHKH6NN2PLRCQ.jpg?auth=b96fceb4acb641eb7765f3f1dff182dfa52eba742065b9da99b560e1ea32da21&width=1200&height=800&quality=80&smart=true"

if not st.user.is_logged_in:
  st.title("Google Login")
  st.image(IMAGE_ADDRESS)
  if st.sidebar.button("Log in with Google", type="primary", icon=":material/login:"):
        st.login()

else:
  st.subheader("Please visit the app")
  if st.sidebar.button("Log out", type="secondary", icon=":material/logout:"):
        st.logout()